---
title: "Shipping manifes ERASE TB "
author: "Laura Böttcher"
date: '`r format(Sys.Date(), "2025-11-11")`'
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: pygments
abstract: Short project description.
knit: (function(inputFile, encoding) {
          rmarkdown::render(inputFile,
                            encoding = encoding, 
                            output_file = paste0(
                              xfun::sans_ext(inputFile), '_', Sys.Date(), '.html'),
                                output_dir = "../results/lab_book/")})
---

```{r setup, include=FALSE}
knitr::opts_knit$set(echo = TRUE, root.dir = getwd(), fig.width = 6, fig.height = 5, warning = FALSE, message = FALSE)

result.dir <- paste0("results/",Sys.Date(),"/")

## creates result.dir with date in if not existent
ifelse(isFALSE(dir.exists(paste0("../",result.dir))), dir.create(paste0("../",result.dir),recursive = TRUE),"Result directory for today exists already!")
options(stringsAsFactors = FALSE) 
```

# Detail
Shipping manifest for Kathrin.
Combine excel and ID to extract the ID and location of the PBMC samples we want to have.



## 1. Needed libraries
```{r message=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)
library(tidyr)
library(readr) # readr is much better with encoding and messy CSVs.
library(janitor)
library(stringr)
library(writexl)
```


### 1.1 Import your data into R
```{r message=FALSE}


Moz <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/ERASE_TB_662_Pax-Plas20251103.csv",
  locale = locale(encoding = "UTF-8")
) %>% janitor::clean_names()

Tan <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/ERASE_TB_663_PLASMA BIOBANKING FINAL SFRZR 25_07_22_006 - Copy (2).csv",
  locale = locale(encoding = "UTF-8")
) %>% janitor::clean_names()

Zim <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/Zim_ERASE-TB_Plasma_ZIM_IDLink_ShippingList.csv",
  locale = locale(encoding = "UTF-8")
) %>% janitor::clean_names()

shipping_id <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/ID list.csv",
  locale = locale(encoding = "UTF-8") # needed when letters with weird caracters like ä, å...
) %>% janitor::clean_names()


Zim1 <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/551_ERASE-TB_Plasma_ZIM_IDLink_ShippingList.csv",
  locale = locale(encoding = "UTF-8")
) %>% janitor::clean_names()


Zim2 <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/552_ERASE-TB_Plasma_ZIM_IDLink_ShippingList.csv",
  locale = locale(encoding = "UTF-8")
) %>% janitor::clean_names()

Zim3 <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/553_ERASE-TB_Plasma_ZIM_IDLink_ShippingList.csv",
  locale = locale(encoding = "UTF-8")
) %>% janitor::clean_names()


```

## 2. shipping ID

```{r}

shipping_id_3 <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/ID_list_3.csv",
  locale = locale(encoding = "UTF-8") # needed when letters with weird caracters like ä, å...
) %>% janitor::clean_names()

shipping_id_long <-shipping_id_3 %>%
  pivot_longer(
    cols = starts_with("id_visit_"),
    names_to = "visit",
    values_to = "id_visit",
    values_drop_na = TRUE
  )

```


```{r message=FALSE}

shipping_id_clean <- shipping_id_long %>%
  filter(
    id_visit != 0 & !is.na(id_visit),
    pers_id != 0 & !is.na(pers_id)
  )


```

```{r}

shipping_id_clean <- shipping_id_clean %>%
  mutate(id_visit_clean = str_replace_all(id_visit, "_", ""))


```

```{r}
shipping_id_clean <- shipping_id_clean%>%
  distinct(id_visit_clean, .keep_all = TRUE)
```

## 3. Tanzania
```{r message=FALSE}

Tan_clean <- Tan %>%
  mutate(participant_id_clean = str_replace_all(participant_id, "-", ""))


```

```{r}


shipping_id_tan <- shipping_id_clean %>%
  left_join(
    Tan_clean %>% select(participant_id_clean, sub_sector_1, sub_sector_2, sub_sector_3),
    by = c("id_visit_clean" = "participant_id_clean")
  ) %>% 
  distinct(id_visit_clean, .keep_all = TRUE)

colnames(shipping_id_tan)[colnames(shipping_id_tan) == "sub_sector_1"] <- "position"
colnames(shipping_id_tan)[colnames(shipping_id_tan) == "sub_sector_2"] <- "rack"
colnames(shipping_id_tan)[colnames(shipping_id_tan) == "sub_sector_3"] <- "box_name"

```

## 4. Mozambique
```{r message=FALSE}
Moz_clean <- Moz %>%
  mutate(participant_id_clean = str_replace_all(participant_id, "-", ""))


```


```{r, filter for the word "plasma" in column}

Moz_clean <- Moz_clean %>%
  filter(str_starts(position_14, "PLASMA"))

```

```{r}


shipping_id_tan_moz <- shipping_id_tan %>%
  left_join(
    Moz_clean %>% select(participant_id_clean, position_12, position_13, position_14),
    by = c("id_visit_clean" = "participant_id_clean")
  ) %>% 
  distinct(id_visit_clean, .keep_all = TRUE)


```


## 5. Zimbabwe

```{r}

Zim <- Zim %>%
  mutate(person_id = as.character(person_id))  

```

```{r message=FALSE}

shipping_id_zim <- shipping_id_tan_moz %>%
  mutate(pers_id = as.character(pers_id)) %>%   # convert BEFORE joining
  left_join(
    Zim %>% 
      mutate(person_id = as.character(person_id)) %>% 
      select(sampleid_plasma, person_id),
    by = c("pers_id" = "person_id")
  ) %>%
  distinct(id_visit_clean, .keep_all = TRUE) %>%
  mutate(
    # Replace last 3 characters with 511
    sampleid_plasma = str_replace(sampleid_plasma, ".{3}$", "511")
  )

```

```{r, combine boxes}

Zim_combined <- bind_rows(Zim1, Zim2, Zim3) %>% 
  distinct(sample_id_number, .keep_all = TRUE)

Zim_combined <- Zim_combined %>%
  mutate(box_number = as.character(box_number))

Zim_combined <- Zim_combined %>%
  mutate(cell = as.character(cell))
```


```{r}

shipping_id_tan_moz_zim <- shipping_id_zim %>%
  mutate(sampleid_plasma = str_trim(as.character(sampleid_plasma))) %>% #remove any leading or trailing spaces in  ID columns and formats it into character
  # perform join only for non-NA sampleid_plasma
  left_join(
    Zim_combined %>%
      mutate(sample_id_number = str_trim(as.character(sample_id_number))) %>% #remove any leading or trailing spaces in  ID columns and formats it into character
      select(box_number, cell, sample_id_number) %>%
      filter(!is.na(sample_id_number)),  # ignore NA in the join column
    by = c("sampleid_plasma" = "sample_id_number")
  )

```

## 7. 
### 7.1 combine all

```{r}
library(janitor)

shipping_id_tan_moz_zim <- shipping_id_tan_moz_zim %>% clean_names()

colnames(shipping_id_tan_moz_zim)

colnames(shipping_id_tan_moz_zim) |> dput()

```
```{r}
shipping_id_final <- shipping_id_tan_moz_zim %>%
  mutate(
    position = coalesce(position, position_12),          # combine position columns
    rack     = coalesce(rack, position_13),              # combine rack with position_13
    box_name = coalesce(box_name, position_14, box_number)  # combine box_name, position_14, box_number
  ) %>%
  select(-position_12, -position_13, -position_14, -box_number)  # remove old columns

```
### 7.2 data export
```{r}
write_xlsx(shipping_id_final, "/Users/laubot/Desktop/Shipping.manifest-extra.xlsx")

```


## 6. SessionInfo
```{r}
## Take environment snapshot 
#renv::snapshot()

sessionInfo()
```

# Shipping 2
```{r}
# This list inclueds 
# control
#Progression/TB
#latent TB
#persistant negative
#persistant positive
#negative to positive (converters)
```

## 1. docunents 
```{r}
shipping_id2 <- read_csv2(
  "/Users/laubot/R studio/TB/data/Shipping manifest ERASE TB/sample id2.csv",
  locale = locale(encoding = "UTF-8") # needed when letters with weird caracters like ä, å...
) %>% janitor::clean_names()

```

## 2. shipping ID
```{r}

shipping_id2_long <- shipping_id2 %>%
  pivot_longer(
    cols = starts_with("id_visit_"),
    names_to = "visit",
    values_to = "id_visit",
    values_drop_na = TRUE
  )

```


```{r message=FALSE}

shipping_id2_clean <- shipping_id2_long %>%
  filter(
    id_visit != 0 & !is.na(id_visit),
    pers_id != 0 & !is.na(pers_id)
  )


```

```{r}

shipping_id2_clean <- shipping_id2_clean %>%
  mutate(id_visit_clean = str_replace_all(id_visit, "_", ""))


```

```{r}
shipping_id2_clean <- shipping_id2_clean%>%
  distinct(id_visit_clean, .keep_all = TRUE)
```

## 3. Tanzania
```{r message=FALSE}

Tan_clean <- Tan %>%
  mutate(participant_id_clean = str_replace_all(participant_id, "-", ""))


```

```{r}


shipping_id2_tan <- shipping_id2_clean %>%
  left_join(
    Tan_clean %>% select(participant_id_clean, sub_sector_1, sub_sector_2, sub_sector_3),
    by = c("id_visit_clean" = "participant_id_clean")
  ) %>% 
  distinct(id_visit_clean, .keep_all = TRUE)

colnames(shipping_id2_tan)[colnames(shipping_id2_tan) == "sub_sector_1"] <- "position"
colnames(shipping_id2_tan)[colnames(shipping_id2_tan) == "sub_sector_2"] <- "rack"
colnames(shipping_id2_tan)[colnames(shipping_id2_tan) == "sub_sector_3"] <- "box_name"

```

## 4. Mozambique
```{r message=FALSE}
Moz_clean <- Moz %>%
  mutate(participant_id_clean = str_replace_all(participant_id, "-", ""))


```


```{r, filter for the word "plasma" in column}

Moz_clean <- Moz_clean %>%
  filter(str_starts(position_14, "PLASMA"))

```

```{r}


shipping_id2_tan_moz <- shipping_id2_tan %>%
  left_join(
    Moz_clean %>% select(participant_id_clean, position_12, position_13, position_14),
    by = c("id_visit_clean" = "participant_id_clean")
  ) %>% 
  distinct(id_visit_clean, .keep_all = TRUE)

```



```{r}

shipping_id2_tan_moz_zim <- shipping_id2_zim %>%
  mutate(sampleid_plasma = str_trim(as.character(sampleid_plasma))) %>% #remove any leading or trailing spaces in  ID columns and formats it into character
  # perform join only for non-NA sampleid_plasma
  left_join(
    Zim_combined %>%
      mutate(sample_id_number = str_trim(as.character(sample_id_number))) %>% #remove any leading or trailing spaces in  ID columns and formats it into character
      select(box_number, cell, sample_id_number) %>%
      filter(!is.na(sample_id_number)),  # ignore NA in the join column
    by = c("sampleid_plasma" = "sample_id_number")
  )

```

## 7. 
### 7.1 combine all

```{r}
library(janitor)

shipping_id2_tan_moz_zim <- shipping_id2_tan_moz_zim %>% clean_names()

colnames(shipping_id2_tan_moz_zim)

colnames(shipping_id2_tan_moz_zim) |> dput()

```
```{r}
shipping_id2_final <- shipping_id2_tan_moz_zim %>%
  mutate(
    position = coalesce(position, position_12),          # combine position columns
    rack     = coalesce(rack, position_13),              # combine rack with position_13
    box_name = coalesce(box_name, position_14, box_number)  # combine box_name, position_14, box_number
  ) %>%
  select(-position_12, -position_13, -position_14, -box_number)  # remove old columns

```
### 7.2 data export
```{r}
write_xlsx(shipping_id2_final, "/Users/laubot/Desktop/Shipping.manifest.3.xlsx")

```



